### ISSUE TITLE
Investigate VDF behavior

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/tlumip#18]
We have a problem with unrealistic behavior and assignment loading. This is related to #14, but probably a separate issue.

**Comment by bstabler** [comment]
Update procedures files so the conical VDFs are calculated so they match Metro's conical VDFs. This means changing the conical(7.0.75) to conical(7,0.98) and the conical(4,0.75) to conical(4,1.21).

**Comment by gregmacfarlane** [comment]
In Nagendra's spreadsheet, the function for the conical function is

```r
2 + sqrt((a^2 * (1 - sat)^2) + b^2) - (a * (1 - sat))
```

So even at zero volume, the travel time is twice the free flow travel time. Is this correct? And if so, is it reasonable?
