### ISSUE TITLE
review link VDF coding

### ISSUE THREAD

**Issue by bstabler** [pbsag/tlumip#34]
ODOT added links without setting the link UDA VDF.  These all need to be reviewed.  The VDF field is used by the SWIM_VISUM_Main.py to code the linkType field for looking up the VDF to use.

**Comment by joshchea** [comment]
To create a fail-safe for this type of coding error... the default value of the UDA -VDF could be set to a given value, this can be done in the UDA definition settings. So it will have 'some' value as a new link is coded... 

Of-course in such cases, the question always is 'is it better to provide this fail-safe so the model runs all the way, or is it better to have the run crash so the coding error is actually discovered, so it doesn't cause problems in calibration downstream' ...

**Comment by bstabler** [comment]
update wiki as well
