### ISSUE TITLE
Update link TypeNo handling for different speeds by mode

### ISSUE THREAD

**Issue by bstabler** [pbsag/tlumip#36]
SWIM_VISUM_Main.py currently calculates link TypeNo since used to lookup the VDF. TypeNo also references the max speed by mode from the link types table, which we're going to need to revise for the Eastern Oregon speed increases.

**Comment by bstabler** [comment]
update procedure files as well

**Comment by bettinardi** [comment]
@bstabler - I have run into an issue.  I am going through and updating all the procedure files and the python script however I have determined that the python script needs an overhaul piece that is above my head.  Currently the script runs a procedure file that contains all the periods saving version files for each period along the way.  This has to be changed as it forces the version file to a set name and we need the ability for that version file name to be flexible.  I need an update to the script that follows one of two options:
1. Either all the steps in the procedure file are fully written into python code, or
2. we build a procedure file for each period (4 procedure files) and the python script calls each one and does the saving and loading of specific file names in-between the procedure file calls, allowing for the name to be a token in the code and not hard coded in the procedure file.  We need this completed fairly quickly (by next week some time).  Please let me know your preference.

**Comment by bettinardi** [comment]
@gregmacfarlane and @bstabler 
A note to the file - 
I just updated (on my side) the network, the SWIM_VISUM_Main.py, linkFieldNames.csv, pathBasedAssignmentSettings_Full.par and initAutoAssignment.par.

The changes address and close issues, 38, 36, 35, and 34.

I would push them to the repo, but this is all currently untested and I will be out for a week, so they are going to sit on my drive until next week.  I will plan to test and push them next week.  

Ben, before these are closed / closed we need to update the procedure files and script to allow for the filename to be changed as I noted above.  Keeping the same file name will no longer be an option as ODOT tries to maintain multiple files across time (years) - it will be an admin nightmare that doesn't need to exist.  Now is the time to fix it so it can be wrapped up with these other large changes.  @bstabler  - I am going to post my file set on the ftp - perhaps you can look at addressing this while I am out.  I am also assigning issue #37 to you. You should take care of that while you are inside "SWIM_VISUM_main.py"

**Comment by bettinardi** [comment]
@bstabler - here's where I put my mid-step revisions.  We can't finalize until we have you help update the script and procedure files:
ftp://ftp.odot.state.or.us/TPAU_SWIM2/NetworkProcedureSetupEdits/

**Comment by gregmacfarlane** [comment]
Can we put these in a branch? Then we can test them and merge easily.
