### ISSUE TITLE
Use ExchangeImportExportW file in t directories

### ISSUE THREAD

**Issue by jeabraham** [pbsag/tlumip#41]
The ret_exchange.py script updates the size term for some allocations based on the quantity of retail space from ALD.  This update currently changes the ExchangeImportExportI.csv file in scenario/inputs/parameters.  Instead, it should follow the standard PECAS workflow, of copying ExchangeImportExportI.csv from scenario/inputs/parameters to scenario/outputs/txx/ExchangeImportExportW.csv, and then make the year-specific changes in this "working" file, indicated with the "W" suffix.  As well, AA needs to be changed to look for the working file in /txx.

**Comment by graham97** [comment]
AA already looked for ExchangeImportExportI in the current year directory before falling back to the inputs directory. Changed retexchange to generate a year-specific ExchangeImportExportI instead of overwriting the input file.
