### ISSUE TITLE
Getting SWIM small back into the update cycle

### ISSUE THREAD

**Issue by bettinardi** [pbsag/tlumip#43]
Hi @gregmacfarlane 

I am working on getting the SWIM small to run again.  When we updated SWIM to pull the correct inputs from the right year we forgot to update the input folders / files for SWIM small.  We also forgot to bring swim small up to Visum 15 (a simple field change in the global template properites.  I just tried to push some changes and they all worked, except the addition of the t21 folder under inputs.  That didn't get picked-up - I assume because I am a folder - not sure if it has to do with the gitignore.  Hoping you can help me figure out how to get the t21 folder created in the swim small folder (it's just a copy of the one in the full scenario).

**Comment by bettinardi** [comment]
@bstabler I can't work any further on the SWIM small - it's stuck in PT and it is not returning any helpful error messages.  I need you to help figure out why the SWIM small is broken.  If you download the current swim small it should work at least up until the PT fail.

**Comment by gregmacfarlane** [comment]
It's not clear what the question is with pushing `inputs/t21`. You can't commit a folder in git; is there anything in it?

If there is something in it that the `.gitignore` is skipping past, open the terminal or git-bash and hit

```bash
git add -f root/scenario/inputs/t21/whateveryourfileis
```

To force-add it to version control.

**Comment by gregmacfarlane** [comment]
I just updated the `.gitignore` file so that the inputs directory should no longer be ignored.

**Comment by bettinardi** [comment]
I tried the line, but no luck - it looked like it worked, but no luck - I am going to try source tree now since you updated the git ignore file.

**Comment by bettinardi** [comment]
never mind, I added, but forgot to push.  Just pushed now in git bash

**Comment by bettinardi** [comment]
Still no luck
