### ISSUE TITLE
AA fails to converge in the final year 

### ISSUE THREAD

**Issue by bettinardi** [pbsag/tlumip#46]
AA fails to converge in the final year (t50) of seemingly every scenario we run.  We need to understand why.  Perhaps it is some imbalance in NED inputs.  We should not have a model that consistently fails to converge.

**Comment by bettinardi** [comment]
I just found out that AA fails to converge in t42 for the optimistic.  That scenario fails in t43.  In my mind this verifies that issues 46 and 47 are one in the same.  To fully verify, we could push the reference to t51 (one year beyond the t50 fail to converge year in the reference), and verify that the model crashes.  We need to figure out what inputs going into AA are unbalanced.

@gregmacfarlane - the answer to this question might help us figure out why the model seems to become so unstable in later years.

**Comment by gregmacfarlane** [comment]
What happens in the quarter ALD? If AA becomes unstable because it has too much space to work with an eventually fails to converge, then we would solve both at the same time.

**Comment by bettinardi** [comment]
The quarter ALD scenario still fails to converge in year t50.  All the scenarios do.  I think it is a NED input issue into AA, as opposed to AA not being able to deal with floorspace.  Something about NED inputs does not make sense (at least not in AA).

**Comment by bettinardi** [comment]
Changed the reference k_12 NED inputs to match the pessimistic scenario.  This should work, but we will verify next week.  See commit - 5fc177feaf45006f939da87750d656eb70c8e491.
