### ISSUE TITLE
Hayden Island zones

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/tlumip#55]
Remove water from buildable land supply.

**Comment by bettinardi** [comment]
Just cleaned up these zones along with some other network issues (a coding problem on a section of I-5 in Washington that I found, and adding Bridge of the Gods).

**Comment by gregmacfarlane** [comment]
Let's close this when the new version is committed.

**Comment by gregmacfarlane** [comment]
Sorry for the mess of openings and closings; I feel like these buttons need to be labeled or designed differently.
