### ISSUE TITLE
Delete unnecessary 7-Zip and R package installers

### ISSUE THREAD

**Issue by rickdonnelly** [pbsag/tlumip#56]
There are several installers in the tlumip/root/model/lib folder that I propose to delete. They include installers for Java, Python, R and several of its packages, and 7-Zip. The README file states that these are maintained to ensure ability to reproduce model results for SWIM system built using those exact versions of software. I know we had issues with Java 6 in the past, where later DAF did not work properly under later minor releases. As far as I know we have had no issues with Java 7, but I'm happy to keep that around, even though Oracle has a website with installers for every past version of Java (including the early Sun release) that we could always grab an older installer from. But we have never had any issues with forward compatibility with Python or R. In the case of the latter the packages in the lib folder are already older than the ones that I'm using in the CT model, for example, and others that I use are not there. Thus, I propose deleting this folder and its contents, except perhaps for the Java installer.

**Comment by bettinardi** [comment]
I disagree with deleting the folder.  While in theory things should be forward compatible, they are always (at least with R).  With R we have had examples of libraries that no longer work correctly in newer versions of R.  I like ensuring that the repository has a copy of everything that the model needs to run - including all the little libraries and dependencies that are required.  That way we don't need to go hunting things down if we ever upgrade machines or whatever - everything is there, and if we decide to get the latest version and it works, great.  But if it doesn't, at least we have a vaulted version of the software that we know works.  So I feel that the 176MBs of space in the "lib" folder is space well saved.

**Comment by gregmacfarlane** [comment]
This is not directly related, but precipitated @rickdonnelly 's question. 

The list of R dependencies (for swimr, ct, etc) is getting quite long and not all packages are on CRAN. Keeping the zipped versions of the source packages in this folder is no longer feasible. We can do one of a few things:

  1. Point the user to download R and run a provided script to install the packages
  2. Provide empty R and have user run a script to install the packages from CRAN
  3. Provide empty R *and* the package source code, with a script to install (*what we do now, which is unsustainable*), with a script to install
  3. Provide R with packages pre-installed

3 is no longer feasible. 4 has the lowest burden but is a maintenance nightmare. Rick is suggesting 1; I think 2 is possible.

**Comment by gregmacfarlane** [comment]
As a note, I will be upgrading swim to R 3.3.1, and will need to do one of these things.

**Comment by rickdonnelly** [comment]
I'm very much for @bettinardi's option 1. We have far more pressing things to focus upon than keeping R installers up to date in our repo. I've only had updates to R itself break two things so far in my life, and they were both in later version 1.x releases. They fixed bugs that were affecting my results in ways I hadn't caught yet. It's inconvenient to deal with them, but no question that the outcome was better as result. It would be easier to catch if we were obsessive about unit testing, but with models as complex as ours it would be close to impossible to catch everything that way.

I am going to convert CT from set of R functions glued together by a runner to a formal R package, as swimr is. As part of that I will converting all of my package dependencies to those in Hadley Wickham's [tidyverse](https://github.com/hadley/tidyverse), which Greg pointed me to yesterday. That will install, update, or load everything I use, with exception of doParallel, in one utility. I presume @gregmacfarlane will do the same with swimr. We can probably write a small R script to install everything we need (tidyverse, doParallel, swimr, ct, ...) that we can include in the SWIM installation wiki and code.

**Comment by bstabler** [comment]
I agree with @bettinardi.  In my experience delivering and maintaining modeling systems, I've found it best to keep a copy of every required piece of software for running the system.  It is also important to keep updated notes on how to set it up.

**Comment by bettinardi** [comment]
Note that ODOT continues to struggle to get packages from non-CRAN sources. Not all of the libraries are on CRAN.  Let's ensure that all R libraries required are in the repo.  I would request that in general we don't trust that a user can access the executables that we point to on the web.  Let's please include the executables used in SWIM in the repo.

**Comment by gregmacfarlane** [comment]
What if we include source zips for non-cran packages, but an installer script for packages that _are_ on CRAN?

**Comment by bettinardi** [comment]
I am okay with that.  
Just remember that SWIM has a pretty long development cycle.  I'm pretty confident that as we moved off of the SDC-6 cluster setup of SWIM 2 the Java version that it was using was no longer available on-line, and if it was, any link breadcrumbs that we would have left ourselves would have been long dead.

I have found it very reassuring to have the required software bundle included, so that everything that is needed is in one spot.  But we did abandon the census data, perhaps we can dump the executables too.  Let's just please do it very very thoughtfully, and ensure that ODOT has safe and dependable access to anything that we are going to cut from the repo.

**Comment by bstabler** [comment]
I think every installer/package/etc. should be in the repo.

**Comment by gregmacfarlane** [comment]
As @bettinardi and @bstabler point out, there is a risk in not having the dependencies stored locally, in that new versions of software may not be backwards-compatible.

There are also risks in keeping a local dependency tree, however. Specifically, if a second-or-third order dependency has a bug that is corrected, the bug fix will never be incorporated automatically. And this is not a hypothetical problem; we repeatedly have to find and fix the same bug in multiple projects. Setup can be annoying, but maintenance becomes torture.

Anyways, I'll close this issue this afternoon with an updated R and package installer script.

**Comment by gregmacfarlane** [comment]
Actually, I'm going to close this when @rickdonnelly puts CT in a package (any day now), and when the tidyverse package gets up on CRAN (should be any day now)

**Comment by bettinardi** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Before you close it on github, let's please run a successful reference test with the new installs.  If a full reference run is too much, let's at least ensure that a swim small completes successfully with the new CT, R package, libraries....

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by gregmacfarlane** [comment]
Planning on it.

**Comment by bettinardi** [comment]
We've started to address this in commit 44a8e36667b50ece144abaa04d418eeedaddef02.
