### ISSUE TITLE
CT seems to lack truck flows in the halo

### ISSUE THREAD

**Issue by bettinardi** [pbsag/tlumip#61]
From as best as I can tell CT is not producing truck flows (originating and destine trips) in the halo zones.  This is espeically problematic for the Portland area which borders the halo and has two key bridges that cross into Washington and are not showing the correct truck traffic flows.  Further this is creating a major issue along SR-14 in Washington, which is the detour option for I-84 in Oregon.  When we close I-84 in Oregon to trucks, SR-14 can handle the traffic without issue, since no Washington trucks need to use the Washington highways.

@rickdonnelly and @gregmacfarlane  - we need to figure out how to get this addressed prior to closing TLUMIP 5.

**Comment by gregmacfarlane** [comment]
I'm digging through the CT output from my most recent scenario run. `ct-internal-truck-origins.Rdata` doesn't have trucks originating in Vancouver, Walla Walla, or Boise. There are also no synthetic firms in those zones.

Is it possible that this code chunk in [`create_synthetic_firms()`](https://github.com/pbsag/tlumip/blob/master/root/scenario/model/code/ct/Create%20synthetic%20firms3.r#L32-L37) the culprit:

```r
    # Next we'll append the county the alpha zone falls within, from which we
    # can add FAF region
    counties <- fread(RTP[["alpha2beta.file"]]) %>%
        filter(STATEFIPS==41) %>%
        mutate(fips = as.numeric(STATEFIPS)*1000+as.numeric(COUNTYFIPS)) %>%
        select(Azone, fips)
```

It seems like we only are generating synthetic firms for zones *inside* Oregon. Or maybe I'm misunderstanding how CT is built.

**Comment by rickdonnelly** [comment]
I cannot replicate this problem from either the older code base that is in the repo or the newer version that I've put into R package format. The firm synthesis is building firms in all zones in the halo that have employment coded (read from Employment.csv, generated by PECAS in each simulation year), and internal truck trips are being generated within those zones. I've checked that this is true for the three zones that @gregmacfarlane fingered for me (4086 in Boise, 980 in Vancouver, and 4061 in Walla Walla). I'm at complete loss as to why those trips are not making the jump to traffic assignment.

In the short term I've put the final truck trip list created by the newer CT (package version) [in Dropbox](https://www.dropbox.com/s/r0w7anw0vwdv00c/Trips_CTTruck.csv?dl=0), which you can download to look through. It includes the fields formerly included in Trips_CTTruck.csv that @bstabler writes out from the existing CT implementation, as well as adding a few new ones (travel time, distance, value, tons, dataset ["faf" for inter-regional trips and "ct" for internal trips] and commodity). The tour and trip modes -- filled with missing values in existing versions -- are re-implemented as originally intended, but we will need to check that string formats coded for them are handled okay by program(s) @bstabler uses to translate them into trip matrices.

Finally, the code @gregmacfarlane fingered above was only used to allocate inter-regional (FAF) trips originating or terminating within Oregon (FAF regions 411 and 419) to alpha zones within the state. I've updated the process in the updated create_synthetic_firms() to add the FAF region as firm attribute, obviating the need for the above code chunk. The practical effect of the code above is that a FAF trip with one trip end coded inside Oregon (and the other outside of it) would never be coded to a zone in the halo, but I think that was intended to work that way. 

Next steps that make most sense to me are:

+ @bettinardi will check that inserting [new trip list](https://www.dropbox.com/s/r0w7anw0vwdv00c/Trips_CTTruck.csv?dl=0) retains truck trips in the halo and doesn't break downstream code.
+ I will work with @gregmacfarlane to build the wrapper that runs the package version of CT in place of the existing version. Once we've worked out the kinks we will replace the CT code in the repo with the updated code.
+ We'll work with @bstabler to ensure that translation from trip list to matrix format is happening like we both expect it to be.
